#! /bin/bash

#Directory Declarations
start_dir=$PWD
sd_image_preset="pieeprom_sd_boot.bin"
usb_image_preset="pieeprom_usb_boot.bin"
clean_image_dir=/usr/bin/eeprom_flasher/clean_images
flash_image_dir=/usr/bin/eeprom_flasher/flash_images
config_dir=/usr/bin/eeprom_flasher/configs

#Color Declarations
std=`tput setaf 15`
red=`tput setaf 9 bold`
green=`tput setaf 10 bold`
yellow=`tput setaf 11 bold`
pink=`tput setaf 63`

#Main Script
echo ""
echo ""
echo "${pink}      /////////  /////////  /////////  ////////  /////////  /////////////${std}"
echo "${pink}     //         //         //     //  //    //  //     //  //    //   //${std}"
echo "${pink}    //         //         //     //  //    //  //     //  //    //   //${std}"
echo "${pink}   /////      /////      /////////  ////////  //     //  //    //   //${std}"
echo "${pink}  //         //         //         //\\\      //     //  //         //${std}"
echo "${pink} //         //         //         //  \\\    //     //  //         //${std}"
echo "${pink}/////////  /////////  //         //    \\\  /////////  //         //${std}"
echo "RPI EEPROM Flasher by Nightstalker for the Kali Linux Distro"
echo ""
echo ""

echo "${red}Clean Images Directory:${std}"
echo $clean_image_dir

echo ""
echo "${red}Flash Images Directory:${std}"
echo $flash_image_dir

echo ""
echo "${red}Configs Directory:${std}"
echo $config_dir

cd $flash_image_dir

echo ""
echo ""
echo "${green}Which Image do you want to flash?${std}"
echo ""

n=1
for f in *; do
        printf "%d. %s\n" $n "${f}"
        flash_image_paths[${n}]=$flash_image_dir"/"${f}
        ((n++))
done

echo ""
read -p "${green}Enter a Number for a File: ${std}" n

while [[ $n -lt 1 || $n -gt ${#flash_image_paths[@]} ]]
do
        echo ""
        echo "${red}Wrong Input! Please Select a Number for a File!${std}"
        read -p "Enter a Number for a File: " n;
done

image_to_flash="${flash_image_paths[$n]}"

echo ""
echo "${green}You selected the following File:${std}"
echo $image_to_flash

echo ""
echo ""
echo "${yellow}ARE YOU SURE YOU WANT TO FLASH THE FOLLOWING IMAGE TO THE EEPROM?${std}"
echo "${yellow}FLASHING A WRONG FILE TO THE EEPROM COULD TOTALLY BRICK YOUR SYSTEM!!${std}"
echo "${red}IMAGE FILE:${std} $image_to_flash"

echo ""
read -p "${green}Yes (y)/ No (n): ${std}" n;

while ! [[ "$n" =~ ^(y|n)$ ]];
do
        echo ""
        echo "${red}Wrong Input! Please type 'y' for 'YES' or 'n' for 'NO'!${std}"
        read -p "Yes (y)/ No (n): " n;
done

if [[ "$n" =~ ^(y)$ ]];
then
        echo ""
        echo ""
        echo "Your Image is being flashed to the EEPROM!"

	echo ""
        sudo rpi-eeprom-update -d -f $image_to_flash

        echo ""
        echo "${green}Finished the total Desctruction of your Raspberry Pi!${std}"
        echo "${green}Exiting Script now!${std}"
        exit 1
else
        echo ""
        echo ""
        echo "${red}Operation Aborted! Your Raspberry Pi is safe!${std}"
        echo "${red}Exiting Script now!${std}"
	exit 1
fi
